sudo: required
language: R
services:
- docker
addons:
  sauce_connect: true
env:
  matrix:
  - NOT_CRAN=true
before_install:
- svn checkout https://github.com/SeleniumHQ/selenium/trunk/common/src/web
- docker run -d -p 3000:8080 --name http-server -v $(pwd)/web:/public redsadic/docker-http-server&
- docker run -d -p 127.0.0.1:4444:4444 --link http-server selenium/standalone-chrome:2.53.1
r:
- oldrel
- release
- devel
after_success:
- Rscript -e 'covr::codecov()'
